### ISSUE TITLE
Conflict with Doctrine Migration Bundle

### ISSUE THREAD

**Issue by chwong1** [broadway/event-store-dbal#11]
When using with Doctrine Migration Bundle (https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html), it always creates a migration that drop the event table.

Any way to resolve this?

**Comment by arrgson** [comment]
```
doctrine:
    dbal:
        schema_filter: ~^(?!event)~
```

**Comment by chwong1** [comment]
Thanks
