### ISSUE TITLE
implement Symfony commands to create and drop event store schema

### ISSUE THREAD

**Issue by othillo** [broadway/event-store-dbal#16]
see https://github.com/broadway/broadway-bundle/issues/29

**Comment by jorge07** [comment]
Why not a migration?

**Comment by othillo** [comment]
This ticket is about the existing commands in the bundle: https://github.com/broadway/broadway-bundle/pull/50/commits/5cc22d5dce4f498c96886f83be53e7838e3130cc

In our opinion it's indeed better to use migrations.

**Comment by bruli** [comment]
I'm starting a new project with broadway, and I'm blocked because commands not exits and we can not create event store.

If we need create a migration, which is the schema to create?.

**Comment by jorge07** [comment]
@bruli same problem here.  The solution I found was: https://github.com/broadway/event-store-dbal/pull/17

**Comment by bruli** [comment]
@jorge07 Thanks for the solution.
But I think documentation needs a update.

**Comment by ToluTourialai** [comment]
Tried the solution of @jorge07 , but keep recieving `You have requested a non-existent service "Broadway\EventStore\Dbal\DBALEventStore".` error when running the migration..
