### ISSUE TITLE
[Proposal] Schema refactor

### ISSUE THREAD

**Issue by jorge07** [broadway/event-store-dbal#18]
Auto-incremental fields lock the table and is currently used for sorting when `recorded_on` exists for that purpose.

The proposal for the schema is:

- Use `recorded_on` for sorting but also set the correct type, `DATETIME || TIMESTAMP` instead string.
- Use JSON fields when possible. Text type for `payload` and `metadata` is much less efficient.
- Remove `id` column

**Comment by othillo** [comment]
relates to https://github.com/broadway/event-store-dbal/issues/7

**Comment by othillo** [comment]
If I'm not mistaken the recorded_on field is a string because it stores a date time with microseconds, see https://github.com/broadway/broadway/blob/master/src/Broadway/Domain/DateTime.php#L25 and https://github.com/broadway/event-store-dbal/blob/master/src/DBALEventStore.php#L160

**Comment by jorge07** [comment]
You're right. What do you think about the rest?

**Comment by othillo** [comment]
The id is used by `prepareVisitEventsStatementWhereAndBindValues` (https://github.com/broadway/event-store-dbal/blob/master/src/DBALEventStore.php#L287)

But I agree the `id` shouldn't be necessary because the real primary key is the combination of `uuid` and `playhead`.
