### ISSUE TITLE
JSON datatype for JSON data

### ISSUE THREAD

**Issue by janwalther** [broadway/event-store-dbal#7]
MySQL supports a [JSON datatype](https://www.sitepoint.com/use-json-data-fields-mysql-databases/) since version 5.7. PostgreSQL since [9.2](https://www.postgresql.org/docs/9.2/static/datatype-json.html). With this data type you can save JSON data and query single fields of this JSON later on. This could help when analysing or debugging stored events.
Any plans on supporting it?

**Comment by othillo** [comment]
That's a nice feature! The maintainers have no plans for implementing this, but we are more than happy to review initiatives from the community.
